apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: njb5kwzia-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: njb5kwzia-python 
  name: njb5kwzia-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: njb5kwzia-python 
